import { apiRequest } from "../query-client";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { Platform } from "react-native";
import { API_URL } from "../config";
import { STORAGE_KEYS } from "../keys";
import type { ConversationDTO, ConversationType, MessageDTO } from "@/shared/schema";

const WS_TOKEN_KEY = "procesoclaro_ws_token";

// ----------------------------------------------------------------
// Conversations
// ----------------------------------------------------------------

export async function getConversations(
  limit = 20,
  offset = 0
): Promise<{ conversations: ConversationDTO[]; total: number }> {
  const params = new URLSearchParams({ limit: String(limit), offset: String(offset) });
  const res = await apiRequest("GET", `/api/chat/conversations?${params}`);
  if (!res.ok) throw new Error("Error al cargar conversaciones");
  return res.json();
}

export async function getUnreadCount(): Promise<number> {
  const res = await apiRequest("GET", "/api/chat/unread-count");
  if (!res.ok) return 0;
  const data = await res.json() as { count: number };
  return data.count ?? 0;
}

export async function getOrCreateConversation(
  targetUserId: string,
  type: ConversationType
): Promise<ConversationDTO> {
  const res = await apiRequest("POST", "/api/chat/conversations", { targetUserId, type });
  if (!res.ok) throw new Error("Error al crear conversación");
  return res.json();
}

export async function getOrCreateSupportConversation(
  targetUserId?: string
): Promise<ConversationDTO> {
  const res = await apiRequest("POST", "/api/chat/support-conversation", targetUserId ? { targetUserId } : undefined);
  if (!res.ok) throw new Error("Error al abrir soporte");
  return res.json();
}

// ----------------------------------------------------------------
// Messages
// ----------------------------------------------------------------

export async function getMessages(
  conversationId: string,
  limit = 20,
  offset = 0
): Promise<MessageDTO[]> {
  const params = new URLSearchParams({ limit: String(limit), offset: String(offset) });
  const res = await apiRequest("GET", `/api/chat/conversations/${conversationId}/messages?${params}`);
  if (!res.ok) throw new Error("Error al cargar mensajes");
  return res.json();
}

export async function sendMessageRest(
  conversationId: string,
  content: string
): Promise<MessageDTO> {
  const res = await apiRequest("POST", `/api/chat/conversations/${conversationId}/messages`, { content });
  if (!res.ok) throw new Error("Error al enviar mensaje");
  return res.json();
}

export async function markConversationRead(conversationId: string): Promise<void> {
  await apiRequest("POST", `/api/chat/conversations/${conversationId}/read`);
}

export async function deleteMessage(messageId: string): Promise<void> {
  const res = await apiRequest("DELETE", `/api/chat/messages/${messageId}`);
  if (!res.ok) throw new Error("Error al eliminar mensaje");
}

// ----------------------------------------------------------------
// File attachments
// ----------------------------------------------------------------

export interface UploadableFile {
  uri: string;
  name: string;
  mimeType: string;
  size: number;
}

/**
 * Upload a file to a chat conversation using XMLHttpRequest so upload
 * progress can be tracked. Returns the MessageDTO inserted by the server.
 *
 * tempId is generated by the caller before the upload starts and included
 * in the server's WS broadcast so the sender can replace the optimistic
 * placeholder without duplication.
 */
export function uploadChatFile(
  conversationId: string,
  procesoId: string | null,
  file: UploadableFile,
  tempId: string,
  onProgress: (pct: number) => void
): Promise<MessageDTO> {
  return new Promise(async (resolve, reject) => {
    let token = await AsyncStorage.getItem(STORAGE_KEYS.AUTH_TOKEN);
    if (!token) token = await AsyncStorage.getItem(STORAGE_KEYS.CLIENT_AUTH_ID);
    if (!token) token = await AsyncStorage.getItem(WS_TOKEN_KEY);

    const formData = new FormData();

    if (Platform.OS === "web") {
      // On web, fetch the blob URI and append a real File object
      const response = await fetch(file.uri);
      const blob = await response.blob();
      formData.append("file", new File([blob], file.name, { type: file.mimeType }));
    } else {
      // On native, the RN XHR bridge handles { uri, name, type } objects
      formData.append("file", { uri: file.uri, name: file.name, type: file.mimeType } as any);
    }

    if (procesoId) formData.append("procesoId", procesoId);
    formData.append("tempId", tempId);

    const baseUrl = API_URL.replace(/\/$/, "");
    const url = `${baseUrl}/api/chat/conversations/${conversationId}/upload`;

    const xhr = new XMLHttpRequest();

    xhr.upload.addEventListener("progress", (event) => {
      if (event.lengthComputable) {
        onProgress(Math.round((event.loaded / event.total) * 100));
      }
    });

    xhr.addEventListener("load", () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        try {
          resolve(JSON.parse(xhr.responseText) as MessageDTO);
        } catch {
          reject(new Error("Respuesta inválida del servidor"));
        }
      } else {
        try {
          const body = JSON.parse(xhr.responseText);
          reject(new Error(body?.error ?? `Error ${xhr.status}`));
        } catch {
          reject(new Error(`Error ${xhr.status}`));
        }
      }
    });

    xhr.addEventListener("error", () => reject(new Error("Error de red al subir archivo")));
    xhr.addEventListener("abort", () => reject(new Error("Subida cancelada")));

    xhr.open("POST", url);
    xhr.withCredentials = true;
    if (token) xhr.setRequestHeader("Authorization", `Bearer ${token}`);
    xhr.send(formData);
  });
}

/**
 * Fetch a 60-second signed download URL for a file message.
 * The backend validates that the caller is a conversation participant.
 */
export async function getFileDownloadUrl(messageId: string): Promise<string> {
  const res = await apiRequest("GET", `/api/chat/messages/${messageId}/download`);
  if (!res.ok) throw new Error("No se pudo obtener el enlace de descarga");
  const { url } = await res.json();
  return url as string;
}
